apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    build.appstudio.openshift.io/application: application-sample-11
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: application-sample-other-11
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: appstudio
  namespace: application-service-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
status: {}
